Like.create!([
  {photo_id: 45, user_id: 6},
  {photo_id: 44, user_id: 6},
  {photo_id: 38, user_id: 2},
  {photo_id: 39, user_id: 2},
  {photo_id: 40, user_id: 2},
  {photo_id: 4, user_id: 2},
  {photo_id: 17, user_id: 2},
  {photo_id: 48, user_id: 2},
  {photo_id: 18, user_id: 2},
  {photo_id: 46, user_id: 2},
  {photo_id: 30, user_id: 2},
  {photo_id: 1, user_id: 3},
  {photo_id: 2, user_id: 3},
  {photo_id: 3, user_id: 3},
  {photo_id: 4, user_id: 3},
  {photo_id: 5, user_id: 3},
  {photo_id: 28, user_id: 9},
  {photo_id: 7, user_id: 3},
  {photo_id: 8, user_id: 3},
  {photo_id: 9, user_id: 3},
  {photo_id: 1, user_id: 4},
  {photo_id: 2, user_id: 4},
  {photo_id: 3, user_id: 4},
  {photo_id: 4, user_id: 4},
  {photo_id: 5, user_id: 4},
  {photo_id: 6, user_id: 4},
  {photo_id: 7, user_id: 4},
  {photo_id: 8, user_id: 4},
  {photo_id: 9, user_id: 4},
  {photo_id: 2, user_id: 5},
  {photo_id: 4, user_id: 5},
  {photo_id: 44, user_id: 9},
  {photo_id: 10, user_id: 9},
  {photo_id: 29, user_id: 9},
  {photo_id: 1, user_id: 6},
  {photo_id: 2, user_id: 6},
  {photo_id: 3, user_id: 6},
  {photo_id: 4, user_id: 6},
  {photo_id: 5, user_id: 6},
  {photo_id: 47, user_id: 9},
  {photo_id: 6, user_id: 6},
  {photo_id: 9, user_id: 1},
  {photo_id: 14, user_id: 9},
  {photo_id: 7, user_id: 6},
  {photo_id: 8, user_id: 6},
  {photo_id: 9, user_id: 6},
  {photo_id: 41, user_id: 9},
  {photo_id: 43, user_id: 9},
  {photo_id: 20, user_id: 9},
  {photo_id: 26, user_id: 9},
  {photo_id: 32, user_id: 9},
  {photo_id: 45, user_id: 9},
  {photo_id: 12, user_id: 9},
  {photo_id: 1, user_id: 8},
  {photo_id: 2, user_id: 8},
  {photo_id: 3, user_id: 8},
  {photo_id: 4, user_id: 8},
  {photo_id: 5, user_id: 8},
  {photo_id: 7, user_id: 8},
  {photo_id: 19, user_id: 9},
  {photo_id: 8, user_id: 8},
  {photo_id: 9, user_id: 8},
  {photo_id: 1, user_id: 9},
  {photo_id: 2, user_id: 9},
  {photo_id: 5, user_id: 9},
  {photo_id: 6, user_id: 9},
  {photo_id: 7, user_id: 9},
  {photo_id: 15, user_id: 9},
  {photo_id: 9, user_id: 9},
  {photo_id: 31, user_id: 9},
  {photo_id: 22, user_id: 9},
  {photo_id: 27, user_id: 9},
  {photo_id: 1, user_id: 11},
  {photo_id: 2, user_id: 11},
  {photo_id: 3, user_id: 11},
  {photo_id: 4, user_id: 11},
  {photo_id: 1, user_id: 12},
  {photo_id: 2, user_id: 12},
  {photo_id: 24, user_id: 9},
  {photo_id: 1, user_id: 13},
  {photo_id: 2, user_id: 13},
  {photo_id: 3, user_id: 13},
  {photo_id: 1, user_id: 14},
  {photo_id: 2, user_id: 14},
  {photo_id: 3, user_id: 14},
  {photo_id: 4, user_id: 14},
  {photo_id: 35, user_id: 9},
  {photo_id: 42, user_id: 9},
  {photo_id: 3, user_id: 15},
  {photo_id: 4, user_id: 15},
  {photo_id: 5, user_id: 15},
  {photo_id: 33, user_id: 9},
  {photo_id: 34, user_id: 9},
  {photo_id: 48, user_id: 9},
  {photo_id: 1, user_id: 17},
  {photo_id: 2, user_id: 17},
  {photo_id: 3, user_id: 17},
  {photo_id: 4, user_id: 17},
  {photo_id: 5, user_id: 17},
  {photo_id: 6, user_id: 17},
  {photo_id: 8, user_id: 1},
  {photo_id: 31, user_id: 1},
  {photo_id: 32, user_id: 1},
  {photo_id: 23, user_id: 1},
  {photo_id: 5, user_id: 1},
  {photo_id: 6, user_id: 1},
  {photo_id: 7, user_id: 1},
  {photo_id: 15, user_id: 1},
  {photo_id: 33, user_id: 1},
  {photo_id: 26, user_id: 1},
  {photo_id: 19, user_id: 1},
  {photo_id: 20, user_id: 1},
  {photo_id: 21, user_id: 1},
  {photo_id: 22, user_id: 1},
  {photo_id: 10, user_id: 1},
  {photo_id: 11, user_id: 1},
  {photo_id: 12, user_id: 1},
  {photo_id: 13, user_id: 1},
  {photo_id: 14, user_id: 1},
  {photo_id: 27, user_id: 1},
  {photo_id: 28, user_id: 1},
  {photo_id: 30, user_id: 1},
  {photo_id: 34, user_id: 1},
  {photo_id: 16, user_id: 1},
  {photo_id: 17, user_id: 1},
  {photo_id: 3, user_id: 1},
  {photo_id: 21, user_id: 2},
  {photo_id: 26, user_id: 2},
  {photo_id: 7, user_id: 2},
  {photo_id: 11, user_id: 2},
  {photo_id: 1, user_id: 2},
  {photo_id: 2, user_id: 2},
  {photo_id: 6, user_id: 2},
  {photo_id: 22, user_id: 2},
  {photo_id: 32, user_id: 2},
  {photo_id: 16, user_id: 2},
  {photo_id: 19, user_id: 2},
  {photo_id: 6, user_id: 3},
  {photo_id: 31, user_id: 3},
  {photo_id: 32, user_id: 3},
  {photo_id: 10, user_id: 3},
  {photo_id: 22, user_id: 3},
  {photo_id: 33, user_id: 3},
  {photo_id: 25, user_id: 3},
  {photo_id: 14, user_id: 3},
  {photo_id: 20, user_id: 3},
  {photo_id: 13, user_id: 3},
  {photo_id: 12, user_id: 3},
  {photo_id: 39, user_id: 3},
  {photo_id: 41, user_id: 3},
  {photo_id: 18, user_id: 18},
  {photo_id: 30, user_id: 18},
  {photo_id: 26, user_id: 18},
  {photo_id: 29, user_id: 18},
  {photo_id: 37, user_id: 18},
  {photo_id: 36, user_id: 18},
  {photo_id: 19, user_id: 8},
  {photo_id: 23, user_id: 8},
  {photo_id: 6, user_id: 8},
  {photo_id: 33, user_id: 8},
  {photo_id: 20, user_id: 8},
  {photo_id: 21, user_id: 8},
  {photo_id: 22, user_id: 8},
  {photo_id: 24, user_id: 8},
  {photo_id: 25, user_id: 8},
  {photo_id: 26, user_id: 8},
  {photo_id: 28, user_id: 8},
  {photo_id: 29, user_id: 8},
  {photo_id: 30, user_id: 8},
  {photo_id: 31, user_id: 8},
  {photo_id: 32, user_id: 8},
  {photo_id: 34, user_id: 8},
  {photo_id: 35, user_id: 8},
  {photo_id: 36, user_id: 8},
  {photo_id: 37, user_id: 8},
  {photo_id: 38, user_id: 8},
  {photo_id: 39, user_id: 8},
  {photo_id: 40, user_id: 8},
  {photo_id: 41, user_id: 8},
  {photo_id: 42, user_id: 8},
  {photo_id: 421, user_id: 8},
  {photo_id: 4211, user_id: 8},
  {photo_id: 42111, user_id: 8},
  {photo_id: 15, user_id: 14},
  {photo_id: 16, user_id: 14},
  {photo_id: 17, user_id: 14},
  {photo_id: 18, user_id: 14},
  {photo_id: 19, user_id: 14},
  {photo_id: 20, user_id: 14},
  {photo_id: 21, user_id: 14},
  {photo_id: 22, user_id: 14},
  {photo_id: 23, user_id: 14},
  {photo_id: 24, user_id: 14},
  {photo_id: 25, user_id: 14},
  {photo_id: 26, user_id: 14},
  {photo_id: 27, user_id: 14},
  {photo_id: 32, user_id: 14},
  {photo_id: 33, user_id: 14},
  {photo_id: 34, user_id: 14},
  {photo_id: 35, user_id: 14},
  {photo_id: 12, user_id: 14},
  {photo_id: 14, user_id: 14},
  {photo_id: 10, user_id: 14},
  {photo_id: 7, user_id: 14},
  {photo_id: 9, user_id: 14},
  {photo_id: 7, user_id: 15},
  {photo_id: 6, user_id: 15},
  {photo_id: 2, user_id: 15},
  {photo_id: 1, user_id: 15},
  {photo_id: 8, user_id: 15},
  {photo_id: 9, user_id: 15},
  {photo_id: 32, user_id: 15},
  {photo_id: 22, user_id: 15},
  {photo_id: 21, user_id: 15},
  {photo_id: 23, user_id: 15},
  {photo_id: 13, user_id: 15},
  {photo_id: 8, user_id: 10},
  {photo_id: 6, user_id: 10},
  {photo_id: 2, user_id: 10},
  {photo_id: 1, user_id: 10},
  {photo_id: 9, user_id: 10},
  {photo_id: 21, user_id: 10},
  {photo_id: 32, user_id: 10},
  {photo_id: 22, user_id: 10},
  {photo_id: 26, user_id: 10},
  {photo_id: 35, user_id: 10},
  {photo_id: 7, user_id: 10},
  {photo_id: 34, user_id: 10},
  {photo_id: 15, user_id: 10},
  {photo_id: 16, user_id: 10},
  {photo_id: 20, user_id: 10},
  {photo_id: 23, user_id: 10},
  {photo_id: 24, user_id: 10},
  {photo_id: 25, user_id: 10},
  {photo_id: 27, user_id: 10},
  {photo_id: 28, user_id: 10},
  {photo_id: 29, user_id: 10},
  {photo_id: 6, user_id: 12},
  {photo_id: 7, user_id: 12},
  {photo_id: 8, user_id: 12},
  {photo_id: 9, user_id: 12},
  {photo_id: 22, user_id: 12},
  {photo_id: 32, user_id: 12},
  {photo_id: 26, user_id: 12},
  {photo_id: 14, user_id: 12},
  {photo_id: 13, user_id: 12},
  {photo_id: 35, user_id: 12},
  {photo_id: 40, user_id: 12},
  {photo_id: 34, user_id: 12},
  {photo_id: 11, user_id: 12},
  {photo_id: 15, user_id: 12},
  {photo_id: 39, user_id: 12},
  {photo_id: 9, user_id: 7},
  {photo_id: 32, user_id: 7},
  {photo_id: 25, user_id: 7},
  {photo_id: 6, user_id: 7},
  {photo_id: 7, user_id: 7},
  {photo_id: 8, user_id: 7},
  {photo_id: 40, user_id: 7},
  {photo_id: 1, user_id: 7},
  {photo_id: 41, user_id: 7},
  {photo_id: 39, user_id: 7},
  {photo_id: 2, user_id: 7},
  {photo_id: 37, user_id: 7},
  {photo_id: 14, user_id: 7},
  {photo_id: 35, user_id: 7},
  {photo_id: 29, user_id: 7},
  {photo_id: 20, user_id: 7},
  {photo_id: 27, user_id: 7},
  {photo_id: 19, user_id: 7},
  {photo_id: 41, user_id: 2},
  {photo_id: 24, user_id: 2},
  {photo_id: 10, user_id: 2},
  {photo_id: 13, user_id: 2},
  {photo_id: 25, user_id: 2},
  {photo_id: 12, user_id: 2},
  {photo_id: 29, user_id: 2},
  {photo_id: 28, user_id: 2},
  {photo_id: 35, user_id: 2},
  {photo_id: 36, user_id: 2},
  {photo_id: 33, user_id: 2},
  {photo_id: 15, user_id: 2},
  {photo_id: 8, user_id: 2},
  {photo_id: 9, user_id: 2},
  {photo_id: 14, user_id: 2},
  {photo_id: 22, user_id: 16},
  {photo_id: 33, user_id: 16},
  {photo_id: 34, user_id: 16},
  {photo_id: 15, user_id: 16},
  {photo_id: 26, user_id: 16},
  {photo_id: 1, user_id: 16},
  {photo_id: 39, user_id: 16},
  {photo_id: 7, user_id: 16},
  {photo_id: 20, user_id: 16},
  {photo_id: 27, user_id: 16},
  {photo_id: 21, user_id: 16},
  {photo_id: 38, user_id: 16},
  {photo_id: 25, user_id: 16},
  {photo_id: 40, user_id: 16},
  {photo_id: 10, user_id: 16},
  {photo_id: 16, user_id: 16},
  {photo_id: 41, user_id: 16},
  {photo_id: 6, user_id: 16},
  {photo_id: 35, user_id: 16},
  {photo_id: 2, user_id: 16},
  {photo_id: 42, user_id: 16},
  {photo_id: 28, user_id: 5},
  {photo_id: 24, user_id: 5},
  {photo_id: 35, user_id: 5},
  {photo_id: 25, user_id: 5},
  {photo_id: 33, user_id: 5},
  {photo_id: 14, user_id: 5},
  {photo_id: 9, user_id: 5},
  {photo_id: 6, user_id: 5},
  {photo_id: 34, user_id: 5},
  {photo_id: 43, user_id: 5},
  {photo_id: 16, user_id: 5},
  {photo_id: 1, user_id: 5},
  {photo_id: 17, user_id: 5},
  {photo_id: 20, user_id: 5},
  {photo_id: 30, user_id: 5},
  {photo_id: 10, user_id: 5},
  {photo_id: 23, user_id: 5},
  {photo_id: 40, user_id: 5},
  {photo_id: 11, user_id: 5},
  {photo_id: 12, user_id: 5},
  {photo_id: 36, user_id: 5},
  {photo_id: 26, user_id: 5},
  {photo_id: 8, user_id: 5},
  {photo_id: 15, user_id: 5},
  {photo_id: 7, user_id: 5}
])
Photo.create!([
  {user_id: 1, review: "Stone pot!", filepicker_url: "https://www.filepicker.io/api/file/ObCTYYaWQyh6N8AxKtBb", place: "Koreana Food, Chestnut Street, Philadelphia, PA, United States", rating: 3, name: "Galbi Bibimbap", menu_item_id: 1, restaurant_id: 1, likes_count: 16},
  {user_id: 1, review: "Cat-nibble-ism! >=(", filepicker_url: "https://www.filepicker.io/api/file/j1HS2xL4TImXEQy1x2zQ", place: "Ramen Bar, Locust Street, Philadelphia, PA, United States", rating: 5, name: "Kitten Bento Box Set", menu_item_id: 2, restaurant_id: 2, likes_count: 16},
  {user_id: 1, review: "bleh. Not my favorite", filepicker_url: "https://www.filepicker.io/api/file/GDNwE7weQ1elSZWiFxRq", place: "HipCityVeg, Philadelphia, PA, United States", rating: 2, name: "Veggie Burger", menu_item_id: 26, restaurant_id: 17, likes_count: 4},
  {user_id: 1, review: "Not actually in Starbucks. Just seed data-ing. heh", filepicker_url: "https://www.filepicker.io/api/file/yrJg8J9QR4O0f21gETIk", place: "Starbucks, Market Street, San Francisco, CA, United States", rating: 4, name: "Xocolatl", menu_item_id: 27, restaurant_id: 18, likes_count: 10},
  {user_id: 1, review: "Tasty, but overpriced.", filepicker_url: "https://www.filepicker.io/api/file/zQYBD2RpRMKxvk76jXSK", place: "Founding Farmers, Park Potomac Avenue, Potomac, MD, United States", rating: 4, name: "Devilish Eggs", menu_item_id: 20, restaurant_id: 15, likes_count: 8},
  {user_id: 1, review: "Exquisite. Perfect brunch appetizers.", filepicker_url: "https://www.filepicker.io/api/file/YkCY0efUS7aBImXAhrJh", place: "White Dog Cafe, Sansom Street, Philadelphia, PA, United States", rating: 5, name: "Lamb Sliders", menu_item_id: 16, restaurant_id: 9, likes_count: 7},
  {user_id: 1, review: "One of the favorites for this restaurant!", filepicker_url: "https://www.filepicker.io/api/file/YxyQTYJTyyO5rwEl9JJT", place: "Greek Lady, South 40th Street, Philadelphia, PA, United States", rating: 5, name: "Spinach Chicken Feta Sandwich", menu_item_id: 14, restaurant_id: 14, likes_count: 6},
  {user_id: 1, review: "THIS IS SO GOOD", filepicker_url: "https://www.filepicker.io/api/file/sVcZvcVVRPa8RU2LLsdm", place: "Kobe Bento, Kearny Street, San Francisco, CA, United States", rating: 3, name: "Kobe Beef", menu_item_id: 5, restaurant_id: 6, likes_count: 14},
  {user_id: 1, review: "I suck with words, but this was really good. ", filepicker_url: "https://www.filepicker.io/api/file/SRmVEvxJQyISD0FO4zEg", place: "Danji, West 52nd Street, New York, NY, United States", rating: 5, name: "Steak Tartare with quail yolk, toasted pine nuts, and Asian pear", menu_item_id: 17, restaurant_id: 7, likes_count: 10},
  {user_id: 1, review: "this is called 고등어조림 (ko-deung-uh-jorim) in korean!", filepicker_url: "https://www.filepicker.io/api/file/uAz3JoGQSuuqqtPd1cQU", place: "Danji, West 52nd Street, New York, NY, United States", rating: 5, name: "Poached Sablefish with Spicy Daikon", menu_item_id: 19, restaurant_id: 7, likes_count: 6},
  {user_id: 1, review: "Don't underestimate this dish. This is the real deal.", filepicker_url: "https://www.filepicker.io/api/file/SgbPGeEKS6eLpNP2dAUX", place: "Founding Farmers, Park Potomac Avenue, Potomac, MD, United States", rating: 5, name: "Chili Dog", menu_item_id: 21, restaurant_id: 15, likes_count: 10},
  {user_id: 1, review: "Ramen Profitable!", filepicker_url: "https://www.filepicker.io/api/file/9hfiWT5uQ8ecX6pqo1tu", place: "Ramen Bar, Locust Street, Philadelphia, PA, United States", rating: 5, name: "Spicy Miso Ramen", menu_item_id: 3, restaurant_id: 2, likes_count: 10},
  {user_id: 1, review: "I love tuna!", filepicker_url: "https://www.filepicker.io/api/file/VOxBqdoTSSZZCr2a7wwR", place: "White Dog Cafe, Sansom Street, Philadelphia, PA, United States", rating: 5, name: "Ahi Tuna", menu_item_id: 9, restaurant_id: 9, likes_count: 4},
  {user_id: 1, review: "This is delicious!", filepicker_url: "https://www.filepicker.io/api/file/nCaG5x1RqewgQ8aSrlSi", place: "Homeskillet, Market Street, San Francisco, CA, United States", rating: 4, name: "Eggs Benedict", menu_item_id: 4, restaurant_id: 5, likes_count: 14},
  {user_id: 1, review: "cheesecake meh", filepicker_url: "https://www.filepicker.io/api/file/DbTqdedAQzytMpgQw9wm", place: "The Cheesecake Factory, Geary Street, San Francisco, CA, United States", rating: 2, name: "Strawberry Cheesecake", menu_item_id: 8, restaurant_id: 8, likes_count: 7},
  {user_id: 1, review: "Is this really from Panda Express? Tbh, no.", filepicker_url: "https://www.filepicker.io/api/file/2HZqSs3URm3QecPYph6w", place: "Panda Express, Market Street, San Francisco, CA, United States", rating: 3, name: "Orange Chicken", menu_item_id: 25, restaurant_id: 16, likes_count: 5},
  {user_id: 1, review: "This is another ramen... so sick", filepicker_url: "https://www.filepicker.io/api/file/prGUnHZ3QYyOZv3atnZI", place: "Ramen Yamadaya, Buchanan Street, San Francisco, CA, United States", rating: 2, name: "Spicy Miso Ramen", menu_item_id: 3, restaurant_id: 4, likes_count: 8},
  {user_id: 1, review: "READ: made-to-order.", filepicker_url: "https://www.filepicker.io/api/file/2t25XUYdQouzXX6sD8Yo", place: "Founding Farmers, Park Potomac Avenue, Potomac, MD, United States", rating: 4, name: "Beignets", menu_item_id: 22, restaurant_id: 15, likes_count: 6},
  {user_id: 1, review: "so much sushi", filepicker_url: "https://www.filepicker.io/api/file/aKzeo2c6QGKN94rfCW8g", place: "Marina Sushi Bar, Lombard Street, San Francisco, CA, United States", rating: 4, name: "Sushi", menu_item_id: 10, restaurant_id: 13, likes_count: 8},
  {user_id: 1, review: "This is sushi", filepicker_url: "https://www.filepicker.io/api/file/fXXVVv9eSau6ZnXInaDI", place: "Sushirrito, New Montgomery Street, San Francisco, CA, United States", rating: 3, name: "Sushi", menu_item_id: 10, restaurant_id: 11, likes_count: 5},
  {user_id: 1, review: "this is so spicy!", filepicker_url: "https://www.filepicker.io/api/file/0ZlED1WLSNuGs9BzRuzn", place: "Ramen Underground, Kearny Street, San Francisco, CA, United States", rating: 5, name: "Spicy Miso Ramen", menu_item_id: 3, restaurant_id: 3, likes_count: 10},
  {user_id: 1, review: "I usually don't get dessert here, but better than expected!", filepicker_url: "https://www.filepicker.io/api/file/JMGvJPIfTwGvngInB506", place: "Greek Lady, South 40th Street, Philadelphia, PA, United States", rating: 4, name: "Salted Caramel Cake", menu_item_id: 13, restaurant_id: 14, likes_count: 3},
  {user_id: 1, review: "THIS IS SO GOOD 2", filepicker_url: "https://www.filepicker.io/api/file/BuMkE7waS1uEMJaRJOx4", place: "Homeskillet, Market Street, San Francisco, CA, United States", rating: 5, name: "Smoked Salmon Bagel", menu_item_id: 6, restaurant_id: 5, likes_count: 11},
  {user_id: 1, review: "<3<3<3", filepicker_url: "https://www.filepicker.io/api/file/uHswK7PeRVy6Ib0dx4l8", place: "Ramen Bar, Locust Street, Philadelphia, PA, United States", rating: 5, name: "Green Tea Ice Cream", menu_item_id: 24, restaurant_id: 2, likes_count: 6},
  {user_id: 1, review: "blah blah", filepicker_url: "https://www.filepicker.io/api/file/X5zQBAQAGmXGOwDEjJ9A", place: "Yuraku Japanese Restaurant, Frederick Road, Germantown, MD, United States", rating: 4, name: "Sushi", menu_item_id: 10, restaurant_id: 12, likes_count: 8},
  {user_id: 1, review: "Tastes like chicken. No it doesn't.", filepicker_url: "https://www.filepicker.io/api/file/jHeHPMVLSnWlOgZP1lcC", place: "Zeppole, North 8th Street, Boise, ID, United States", rating: 4, name: "Zeppole", menu_item_id: 28, restaurant_id: 19, likes_count: 8},
  {user_id: 1, review: "Interesting aesthetics, even more interesting taste.", filepicker_url: "https://www.filepicker.io/api/file/cZiXgFiqQVuLd3h4wBpX", place: "Danji, West 52nd Street, New York, NY, United States", rating: 4, name: "Tofu with Scallion Dressing", menu_item_id: 18, restaurant_id: 7, likes_count: 6},
  {user_id: 1, review: "A classic take-out food place near 40th and Locust!", filepicker_url: "https://www.filepicker.io/api/file/I8yqVJn9RZFQFUfZzoG6", place: "Greek Lady, South 40th Street, Philadelphia, PA, United States", rating: 4, name: "House Gyro", menu_item_id: 11, restaurant_id: 14, likes_count: 6},
  {user_id: 1, review: "Nothing special.", filepicker_url: "https://www.filepicker.io/api/file/bZvOLPfWSPuBNTy6k0zf", place: "Greek Lady, South 40th Street, Philadelphia, PA, United States", rating: 3, name: "Greek Salad with Chicken", menu_item_id: 12, restaurant_id: 14, likes_count: 4},
  {user_id: 1, review: "This is so good", filepicker_url: "https://www.filepicker.io/api/file/EjJtLk4RRVu6ahKymI6g", place: "Fat Salmon Sushi, Walnut Street, Philadelphia, PA, United States", rating: 5, name: "Sushi", menu_item_id: 10, restaurant_id: 10, likes_count: 6},
  {user_id: 1, review: "So much better than it looks. Trust me.", filepicker_url: "https://www.filepicker.io/api/file/l88p4XM5SiKRf3Md027w", place: "White Dog Cafe, Sansom Street, Philadelphia, PA, United States", rating: 5, name: "Lentil Soup", menu_item_id: 15, restaurant_id: 9, likes_count: 9},
  {user_id: 1, review: "Deserving of its Michelin Star", filepicker_url: "https://www.filepicker.io/api/file/xGMNVS4WTNuZGoWXM8ZC", place: "Danji, West 52nd Street, New York, NY, United States", rating: 5, name: "Hamburger", menu_item_id: 7, restaurant_id: 7, likes_count: 13},
  {user_id: 1, review: "What do you call cheese that isn't yours? Nacho cheese!", filepicker_url: "https://www.filepicker.io/api/file/ErXKah3mTe4ABKfpohA3", place: "Distrito, Chestnut Street, Philadelphia, PA, United States", rating: 5, name: "Nachos", menu_item_id: 29, restaurant_id: 20, likes_count: 7},
  {user_id: 2, review: "According to Men's Health Magazine, this burger is one of the fattiest burgers you can buy with money. My diet begins tomorrow.", filepicker_url: "https://www.filepicker.io/api/file/3Vt8f3JxTTKGdn8OjPcX", place: "Carl's Jr. / Green Burrito, United Nations Plaza, San Francisco, CA, United States", rating: 5, name: "Guacamole Burger", menu_item_id: 33, restaurant_id: 24, likes_count: 3},
  {user_id: 5, review: "So gooddddd", filepicker_url: "https://www.filepicker.io/api/file/p2tvkcLSQqvSWtRdiNkg", place: "Lobster Joint, Manhattan Avenue, Brooklyn, NY, United States", rating: 4, name: "Lobster Creole", menu_item_id: 39, restaurant_id: 30, likes_count: 2},
  {user_id: 3, review: "Who knew that Cancun had such AMAZING omelettes!? The BEST that I ever had.", filepicker_url: "https://www.filepicker.io/api/file/Obj5qry0QqeiNO8wRMlU", place: "Live Aqua Cancun, Zona Hotelera, Cancún, Mexico", rating: 5, name: "Omelette!", menu_item_id: 34, restaurant_id: 25, likes_count: 6},
  {user_id: 6, review: "This looks too healthy and green. Dat exposure + contrast doe.", filepicker_url: "https://www.filepicker.io/api/file/nWartMXjTvpu1eNJ285Q", place: "Home, 12th Avenue, San Francisco, CA, United States", rating: 2, name: "Veggie Wrap", menu_item_id: 42, restaurant_id: 28, likes_count: 1},
  {user_id: 2, review: "Wait, why can't my food look like this everyday?", filepicker_url: "https://www.filepicker.io/api/file/8F2nGfHRdKdJG1JQ924Q", place: "Whole Beast The, Victoria, BC, Canada", rating: 4, name: "Greek-style Lamb Salad", menu_item_id: 36, restaurant_id: 27, likes_count: 6},
  {user_id: 2, review: "Okay, not bad. My foray into vegetarianism(?)!", filepicker_url: "https://www.filepicker.io/api/file/eV1skmO1QkyJyWW7nF7f", place: "Veggie Garden, West El Camino Real, Mountain View, CA, United States", rating: 3, name: "Quinoa Salad", menu_item_id: 43, restaurant_id: 31, likes_count: 2},
  {user_id: 2, review: "Edo, ergo sum.", filepicker_url: "https://www.filepicker.io/api/file/mMbj23EUTEeQZPDXZZik", place: "Pizza Hut, Geary Street, San Francisco, CA, United States", rating: 4, name: "Pizza", menu_item_id: 35, restaurant_id: 26, likes_count: 6},
  {user_id: 6, review: "The real me never eats salad. Minsoo is putting words into my mouth.", filepicker_url: "https://www.filepicker.io/api/file/OuEhi8kDQpmNiw6uR6pZ", place: "Home, 12th Avenue, San Francisco, CA, United States", rating: 4, name: "Salad", menu_item_id: 41, restaurant_id: 28, likes_count: 1},
  {user_id: 1, review: "this is so good. this is the best thing on the menu. get it.", filepicker_url: "https://www.filepicker.io/api/file/blRLjh2QFWnkbOEljuyR", place: "Founding Farmers, Park Potomac Avenue, Potomac, MD, United States", rating: 5, name: "Prosciutto, Fig, Mascarpone flat bread", menu_item_id: 23, restaurant_id: 15, likes_count: 6},
  {user_id: 5, review: "I eat this everyday for lunch, and I am so sick of it.", filepicker_url: "https://www.filepicker.io/api/file/ReiSqDR7SEqjFBBB4fuy", place: "SUBWAY® Restaurants, Folsom Street, San Francisco, CA, United States", rating: 2, name: "Over-Roasted Chicken Subway", menu_item_id: 38, restaurant_id: 29, likes_count: 2},
  {user_id: 6, review: "I can make quiche. what can YOU make?", filepicker_url: "https://www.filepicker.io/api/file/4yoz1sc3Rz6msnGp470g", place: "Home, 12th Avenue, San Francisco, CA, United States", rating: 5, name: "Spinach, Ham, and Parmesan Quiche", menu_item_id: 40, restaurant_id: 28, likes_count: 2},
  {user_id: 18, review: "I've given up on life.", filepicker_url: "https://www.filepicker.io/api/file/yH4K7L7QDhPZdpCnr2pg", place: "McDonald's, Walnut Street, Philadelphia, PA 19104, United States", rating: 2, name: "Big Mac", menu_item_id: 31, restaurant_id: 22, likes_count: 4},
  {user_id: 18, review: "Give us this day, our daily bread...", filepicker_url: "https://www.filepicker.io/api/file/6IxjpEumRN23Eh92pzUM", place: "Burger King, Market Street, San Francisco, CA, United States", rating: 2, name: "Whopper Combo", menu_item_id: 32, restaurant_id: 23, likes_count: 3},
  {user_id: 8, review: "I am not usually a huge ribs fan (I know, I know), but I LOVED it here!", filepicker_url: "https://www.filepicker.io/api/file/YVSMQrcSQW6IDPVf2AH9", place: "Baby Blues BBQ, Sansom Street, Philadelphia, PA, United States", rating: 5, name: "Baby Back Ribs", menu_item_id: 30, restaurant_id: 21, likes_count: 9},
  {user_id: 16, review: "This is my favorite cereal. I am not even kidding. Seriously.", filepicker_url: "https://www.filepicker.io/api/file/hTVQtZpqQ7CUvv1syh8i", place: "Home, 12th Avenue, San Francisco, CA, United States", rating: 5, name: "Lucky Charms", menu_item_id: 37, restaurant_id: 28, likes_count: 2}
])
MenuItem.create!([
  {name: "Galbi Bibimbap", price: nil},
  {name: "Kitten Bento Box Set", price: nil},
  {name: "Spicy Miso Ramen", price: nil},
  {name: "Eggs Benedict", price: nil},
  {name: "Kobe Beef", price: nil},
  {name: "Smoked Salmon Bagel", price: nil},
  {name: "Hamburger", price: nil},
  {name: "Strawberry Cheesecake", price: nil},
  {name: "Ahi Tuna", price: nil},
  {name: "Sushi", price: nil},
  {name: "House Gyro", price: nil},
  {name: "Greek Salad with Chicken", price: nil},
  {name: "Salted Caramel Cake", price: nil},
  {name: "Spinach Chicken Feta Sandwich", price: nil},
  {name: "Lentil Soup", price: nil},
  {name: "Lamb Sliders", price: nil},
  {name: "Steak Tartare with quail yolk, toasted pine nuts, and Asian pear", price: nil},
  {name: "Tofu with Scallion Dressing", price: nil},
  {name: "Poached Sablefish with Spicy Daikon", price: nil},
  {name: "Devilish Eggs", price: nil},
  {name: "Chili Dog", price: nil},
  {name: "Beignets", price: nil},
  {name: "Prosciutto, Fig, Mascarpone flat bread", price: nil},
  {name: "Green Tea Ice Cream", price: nil},
  {name: "Orange Chicken", price: nil},
  {name: "Veggie Burger", price: nil},
  {name: "Xocolatl", price: nil},
  {name: "Zeppole", price: nil},
  {name: "Nachos", price: nil},
  {name: "Baby Back Ribs", price: nil},
  {name: "Big Mac", price: nil},
  {name: "Whopper Combo", price: nil},
  {name: "Guacamole Burger", price: nil},
  {name: "Omelette!", price: nil},
  {name: "Pizza", price: nil},
  {name: "Greek-style Lamb Salad", price: nil},
  {name: "Lucky Charms", price: nil},
  {name: "Over-Roasted Chicken Subway", price: nil},
  {name: "Lobster Creole", price: nil},
  {name: "Spinach, Ham, and Parmesan Quiche", price: nil},
  {name: "Salad", price: nil},
  {name: "Veggie Wrap", price: nil},
  {name: "Quinoa Salad", price: nil}
])
Restaurant.create!([
  {name: "Koreana Food, Chestnut Street, Philadelphia, PA, United States", rating: 3},
  {name: "Ramen Bar, Locust Street, Philadelphia, PA, United States", rating: 5},
  {name: "Ramen Underground, Kearny Street, San Francisco, CA, United States", rating: 5},
  {name: "Ramen Yamadaya, Buchanan Street, San Francisco, CA, United States", rating: 2},
  {name: "Homeskillet, Market Street, San Francisco, CA, United States", rating: 4},
  {name: "Kobe Bento, Kearny Street, San Francisco, CA, United States", rating: 3},
  {name: "Danji, West 52nd Street, New York, NY, United States", rating: 4},
  {name: "The Cheesecake Factory, Geary Street, San Francisco, CA, United States", rating: 2},
  {name: "White Dog Cafe, Sansom Street, Philadelphia, PA, United States", rating: 5},
  {name: "Fat Salmon Sushi, Walnut Street, Philadelphia, PA, United States", rating: 5},
  {name: "Sushirrito, New Montgomery Street, San Francisco, CA, United States", rating: 3},
  {name: "Yuraku Japanese Restaurant, Frederick Road, Germantown, MD, United States", rating: 4},
  {name: "Marina Sushi Bar, Lombard Street, San Francisco, CA, United States", rating: 4},
  {name: "Greek Lady, South 40th Street, Philadelphia, PA, United States", rating: 4},
  {name: "Founding Farmers, Park Potomac Avenue, Potomac, MD, United States", rating: 4},
  {name: "Panda Express, Market Street, San Francisco, CA, United States", rating: 3},
  {name: "HipCityVeg, Philadelphia, PA, United States", rating: 2},
  {name: "Starbucks, Market Street, San Francisco, CA, United States", rating: 4},
  {name: "Zeppole, North 8th Street, Boise, ID, United States", rating: 4},
  {name: "Distrito, Chestnut Street, Philadelphia, PA, United States", rating: 5},
  {name: "Baby Blues BBQ, Sansom Street, Philadelphia, PA, United States", rating: 5},
  {name: "McDonald's, Walnut Street, Philadelphia, PA 19104, United States", rating: 2},
  {name: "Burger King, Market Street, San Francisco, CA, United States", rating: 2},
  {name: "Carl's Jr. / Green Burrito, United Nations Plaza, San Francisco, CA, United States", rating: 5},
  {name: "Live Aqua Cancun, Zona Hotelera, Cancún, Mexico", rating: 5},
  {name: "Pizza Hut, Geary Street, San Francisco, CA, United States", rating: 4},
  {name: "Whole Beast The, Victoria, BC, Canada", rating: 4},
  {name: "Home, 12th Avenue, San Francisco, CA, United States", rating: 4},
  {name: "SUBWAY® Restaurants, Folsom Street, San Francisco, CA, United States", rating: 2},
  {name: "Lobster Joint, Manhattan Avenue, Brooklyn, NY, United States", rating: 4},
  {name: "Veggie Garden, West El Camino Real, Mountain View, CA, United States", rating: 3}
])
User.create!([
  {username: "markov", email: "markov@gmail.com", password_digest: "$2a$10$cKLeovmNr94KVPqtOWDLZOxyLrgCAtGTOxepavJnXAS375LPUrjmu", session_token: "TeYG5R5FgPHCnvrOPaaaGg"},
  {username: "minsoo", email: "minsoo91@gmail.com", password_digest: "$2a$10$vpvtMy7yhlYXirVVK.z1OOgkPQ8zdQiPOns6ry10xcG3lYMJsax1W", session_token: "LaTJ-f0yuG4LY2qceWxP9A"},
  {username: "woori", email: "woorib@gmail.com", password_digest: "$2a$10$Pn.6Bihjh1ZRBLwF10Gutu2nc3Zmg2NvwPn2.HvTDmFQax0py/vFm", session_token: "nu06T2v6-tCqQWrnjCH1fA"},
  {username: "dave", email: "dave@gmail.com", password_digest: "$2a$10$Mx0UruWnwwlHVfto7t8LjO2Dmrsk5xHK7z2Xi1HiwkYdIj7AontVy", session_token: "MsBlekTpOMSa3S1WuadXNQ"},
  {username: "philip", email: "philip@gmail.com", password_digest: "$2a$10$DbE6hgl.1bIfZHsxBraXe.I3j.Km0eVI083.4wOHkPbF.nZpS5raS", session_token: "bmBxtwfRrxe4HVXvlzORYA"},
  {username: "michael", email: "michael@gmail.com", password_digest: "$2a$10$o5aWFY.ZsBC/yV0cPrVy8esYSrivLYWmQRFA1Ip7g5FJu8zmNfPO6", session_token: "ipTeI7wVuUjGK8-63FpibA"},
  {username: "hannah", email: "hannah@gmail.com", password_digest: "$2a$10$EtZ8jQqqw4u2v0/vnXE.Qu/b200mdqOM0Hn3KqK7zSctHTJ2K8CXK", session_token: "4idw6NzJrTpwUrgnpR8W4Q"},
  {username: "emily", email: "emily@gmail.com", password_digest: "$2a$10$6NszypoyYXXm8jvvyzfsyuCngjK23cNZivNJSMVWiKJGONwvDFyNq", session_token: "kiytO4PL60SICj_gCz3f-w"},
  {username: "megan", email: "megan@gmail.com", password_digest: "$2a$10$xXthaSZ8w863Dja4UkcsZ.gjgm0Aihbs1hKXwjZs.u5flNtkcNqeC", session_token: "kWyOQFh845JzPUuB0O58NA"},
  {username: "earl", email: "earl@gmail.com", password_digest: "$2a$10$G8/CDAukZhsDB2u6wjRDl.9tzdc.1Wsv60WWiakVhZ.h.tdgsipyK", session_token: "kqNgRabENLqNjtype8rsLg"},
  {username: "jessica", email: "jessica@gmail.com", password_digest: "$2a$10$OzYs7tMP9G1ZPq1nP3CEAODoWyqcFN.DQ.Wts5tDYnh4yAA7Tpa/y", session_token: "ypUUmvtMrgK3vQ4YHvOB9g"},
  {username: "charles", email: "charles@gmail.com", password_digest: "$2a$10$jE7Pjp/c//rMdjl/VcWiSOO9IBHkeN41LNKJ12X/UpFP9u1uTIvzW", session_token: "AR9A8bpyHqCxYvE8Yue5hA"},
  {username: "andrew", email: "andrew@gmail.com", password_digest: "$2a$10$/mvM.AePgNLQxi7lUyyYaemQwzZbWUSGtSKj5aHNsnPDiwi/P7dFq", session_token: "CbktJDPOQkjRxhuybaM7wQ"},
  {username: "jackie", email: "jackie@gmail.com", password_digest: "$2a$10$FTJc2SvWLlrJvidnXUiofOiVOJcPyPPTkF6hIS.FeHyXc8TGzvDCy", session_token: "eRCOeNx6PHmq4ePJ4OfOyQ"},
  {username: "vanessa", email: "vanessa@gmail.com", password_digest: "$2a$10$wtSKd7lLZLQHuO17dXTM7uqDqFhtUOmt459UIJhqJWayq4EHAVcBW", session_token: "NWZYRIb8wK0--mnmGs8oPw"},
  {username: "miley", email: "miley@gmail.com", password_digest: "$2a$10$I3fR4mH7bheyiM1odpzIHOLBZv8g76F9udTxAaV.SQPFM1JrvaTuy", session_token: "1d1aiZrDX7bdl_GtJycm-Q"},
  {username: "taylor", email: "taylor@gmail.com", password_digest: "$2a$10$PELOAHmAex0ALAFqzm9wCeFR7UCSa47jifNrFqF1Qw7G1IM4.3lKC", session_token: "sRQ3J0cR89NU-SkPdzIZ7A"},
  {username: "alex", email: "alex@gmail.com", password_digest: "$2a$10$44hexqycGq7qSrRqqnNWvuxsiNJeo1sXYxH5yDbOynfKXKVw.3qQW", session_token: "asoJd5Rr_DbgXb7jJ1m2kQ"}
])
